version: "3.9"

services:
  app:
    container_name: tet4
    build:
      context: .
      dockerfile: Dockerfile
    command: bash
    volumes:
      - ./app:/myapp
    ports:
      - 3000:3000
    tty: true
