version: "3.9"

services:
  app:
    container_name: tet4
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "rails db:setup RAILS_ENV=development && rails webpacker:compile && rails server -b 0.0.0.0"
    ports:
      - 3000:3000
    tty: true
